version: 2
updates:
- package-ecosystem: composer
  directory: "/"
  schedule:
    interval: daily
    timezone: Europe/Lisbon
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: symplify/easy-coding-standard
    versions:
    - 9.1.1
    - 9.1.3
    - 9.1.4
    - 9.1.5
    - 9.1.9
    - 9.2.1
    - 9.2.10
    - 9.2.11
    - 9.2.13
    - 9.2.14
    - 9.2.15
    - 9.2.17
    - 9.2.18
    - 9.2.19
    - 9.2.2
    - 9.2.23
    - 9.2.4
    - 9.2.5
    - 9.2.6
  - dependency-name: phpunit/phpunit
    versions:
    - 9.5.3
  - dependency-name: pdepend/pdepend
    versions:
    - 2.9.0
